### ISSUE TITLE
Waiting for release:)

### ISSUE THREAD

**Issue by LawrenceXia2008** [sunxm2357/VideoIQ#1]
:)

**Comment by sunxm2357** [comment]
Thanks for your interest! Hopefully, we will release the code in Nov.

**Comment by VanChilly** [comment]
> Thanks for your interest! Hopefully, we will release the code in Nov.

only 18 days left :)

**Comment by dreamerlin** [comment]
Waiting for release

**Comment by touristourist** [comment]
> Thanks for your interest! Hopefully, we will release the code in Nov.

only 13 days left :)

**Comment by sunxm2357** [comment]
Hi all, the code is here!
